version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: educore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_mgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: educore_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: educore_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/school_mgmt?schema=public
      REDIS_URL: redis://redis:6379
      AI_SERVICE_URL: http://ai-service:8000
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-d28ef57d81f1a2fb0f607a96074610eb64cfa7dfe07d6ffc237b41eaa1e50641}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-a164b704388121da6af75ff49b6dbd675ae2dfd5551e3d7dd81eea7bf217a9ad}
      PORT: 4000
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: educore_ai
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      AI_API_KEY: dev-key-change-me
      BACKEND_URL: http://backend:4000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: educore_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
      NEXT_PUBLIC_SOCKET_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
