import { UserRole } from '@school-mgmt/shared';

export const Role = {
  [UserRole.SUPER_ADMIN]: [
    '*',
  ],
  [UserRole.ADMIN]: [
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'class:read',
    'class:create',
    'class:update',
    'class:delete',
    'subject:read',
    'subject:create',
    'subject:update',
    'subject:delete',
    'enrollment:read',
    'enrollment:create',
    'enrollment:update',
    'enrollment:delete',
    'attendance:read',
    'attendance:create',
    'attendance:update',
    'grade:read',
    'grade:create',
    'grade:update',
    'fee:read',
    'fee:create',
    'fee:update',
    'event:read',
    'event:create',
    'event:update',
    'event:delete',
    'timetable:read',
    'timetable:create',
    'timetable:update',
    'timetable:delete',
    'notification:read',
    'notification:create',
    'announcement:read',
    'announcement:create',
    'health:read',
    'health:create',
    'report:read',
    'report:export',
  ],
  [UserRole.TEACHER]: [
    'user:read',
    'class:read',
    'subject:read',
    'attendance:read',
    'attendance:create',
    'grade:read',
    'grade:create',
    'grade:update',
    'assignment:read',
    'assignment:create',
    'assignment:update',
    'timetable:read',
    'event:read',
    'event:create',
    'announcement:read',
    'announcement:create',
    'notification:read',
    'report:read',
    'health:read',
    'ai:use',
  ],
  [UserRole.STUDENT]: [
    'user:read',
    'class:read',
    'subject:read',
    'attendance:read',
    'grade:read',
    'assignment:read',
    'assignment:submit',
    'timetable:read',
    'event:read',
    'notification:read',
    'ai:use',
  ],
  [UserRole.PARENT]: [
    'user:read',
    'class:read',
    'attendance:read',
    'grade:read',
    'assignment:read',
    'timetable:read',
    'event:read',
    'notification:read',
    'fee:read',
    'ai:use',
  ],
} as const;

export const PERMISSIONS = {
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  CLASS_READ: 'class:read',
  CLASS_CREATE: 'class:create',
  CLASS_UPDATE: 'class:update',
  CLASS_DELETE: 'class:delete',
  SUBJECT_READ: 'subject:read',
  SUBJECT_CREATE: 'subject:create',
  SUBJECT_UPDATE: 'subject:update',
  SUBJECT_DELETE: 'subject:delete',
  ENROLLMENT_READ: 'enrollment:read',
  ENROLLMENT_CREATE: 'enrollment:create',
  ENROLLMENT_UPDATE: 'enrollment:update',
  ENROLLMENT_DELETE: 'enrollment:delete',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_CREATE: 'attendance:create',
  ATTENDANCE_UPDATE: 'attendance:update',
  GRADE_READ: 'grade:read',
  GRADE_CREATE: 'grade:create',
  GRADE_UPDATE: 'grade:update',
  FEE_READ: 'fee:read',
  FEE_CREATE: 'fee:create',
  FEE_UPDATE: 'fee:update',
  EVENT_READ: 'event:read',
  EVENT_CREATE: 'event:create',
  EVENT_UPDATE: 'event:update',
  EVENT_DELETE: 'event:delete',
  TIMETABLE_READ: 'timetable:read',
  TIMETABLE_CREATE: 'timetable:create',
  TIMETABLE_UPDATE: 'timetable:update',
  TIMETABLE_DELETE: 'timetable:delete',
  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_CREATE: 'notification:create',
  ANNOUNCEMENT_READ: 'announcement:read',
  ANNOUNCEMENT_CREATE: 'announcement:create',
  HEALTH_READ: 'health:read',
  HEALTH_CREATE: 'health:create',
  REPORT_READ: 'report:read',
  REPORT_EXPORT: 'report:export',
  AI_USE: 'ai:use',
} as const;